server:
  port: 9000

languages:
  school-users:
    - username: michael
      password: geheim
      authorities: ROLE_USER, ROLE_LANGUAGE_GERMAN
    - username: stacey
      password: secret
      authorities: ROLE_USER, ROLE_LANGUAGE_ENGLISH
    - username: admin
      password: admin
      authorities: ROLE_ADMIN
messages:
  everyone: Online Language School.
  languages: Our available languages are German and English.
  german: Willkommen
  english: Welcome

interactions:
  amount: 100
  delay: 5000

