server:
  port: 9002
available:
  diagnoses:
    - name: allergy
      symptoms: sneezing, nasal congestion
    - name: anemia
      symptoms: fatigue, appear pale
    - name: anxiety
      symptoms: stress, irritability


