spring:
  data:
    mongodb:
      uri: mongodb://localhost/small-business
server:
  port: 8500
credentials:
  shopUsers:
    - username: owner
      password: owner
      authorities: ROLE_OWNER
    - username: premium
      password: premium
      authorities: ROLE_PREMIUM
