spring:
  data:
    mongodb:
      uri: mongodb://localhost/small-business
server:
  port: 8500

credentials:
  shopUsers:
    - username: owner
      password: owner
      authorities: ROLE_OWNER
    - username: premium
      password: premium
      authorities: ROLE_PREMIUM
shop:
  opening: "0 0 9 * * MON-FRI"
  closing: "0 0 17 * * MON-FRI"
  rate: "10000"