server:
  port: 9001
registered:
  users:
    - name: Lisa
      email: lisa@email.com
      accounttype: standard
    - name: Rodolfo
      email: rodolfo@email.com
      accounttype: standard
    - name: Samuel
      email: samuel@email.com
      accounttype: premium
    - name: Rose
      email: rose@email.com
      accounttype: premium
