server:
  port: 9100

spring:
  data:
    mongodb:
      uri: mongodb://localhost/steam-users

steam-users:
  steam-app:
    username: steamapp
    password: steamapp
    authorities: ROLE_APP
  regular:
    authorities: ROLE_USER
    message: Login successful
